title: Testing Jekyll
author: TiSli
email: secretemail@secretdomain.nl
description: > # this means to ignore newlines until "baseurl:"Timo Slinger, born in Amsterdam, the Netherlands in 1987
  

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
